<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Machine_Learning</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Reinforcement\" />
    <Folder Include="Supervised\Classification\" />
    <Folder Include="Unsupervised\" />
  </ItemGroup>

</Project>
